// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://annncygiephvognqttau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFubm5jeWdpZXBodm9nbnF0dGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzQ0ODMsImV4cCI6MjA2MTQxMDQ4M30.kqkWlh-ABziseBkfu71a9n3Dal4x1ZujJ2MDdiSLhws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);